<?php
// $Id: filefield_insert.install,v 1.1 2009/05/08 19:05:33 quicksketch Exp $

/**
 * @file
 * Update and install functions for FileField Insert.
 */

/**
 * Implementation of hook_install().
 */
function filefield_insert_install() {
  // FileField Insert needs to load after both ImageField and FileField.
  db_query("UPDATE {system} SET weight = 15 WHERE type = 'module' AND name = 'filefield_insert'");
}
